### ISSUE TITLE
X axis 90° different

### ISSUE THREAD

**Issue by ghost** [tomysshadow/Shockwave-3D-World-Converter#7] opened 2023-01-16 22:48 UTC
Hi

When loading any OBJ file, convert from W3D, into Blender or Godot, I saw the OBJ must be rotated 90° on the X axis because the model is not in the correct position.
Do you have this problem too and what 3D program you use to load the OBJ?
Could this be a small bug for the X coordinates of the model?

Here is a screenshot on how an arcade cabinet is opened without rotating it.
You see I have to rotate it 90° around the X axis (red one)

![afbeelding](https://user-images.githubusercontent.com/122493908/212776250-b88f3893-599e-468f-8ff5-2b5fee384ef9.png)

**Comment by tomysshadow** [comment] 2023-01-16 23:36
This is not an issue I've encountered with the worlds you sent or any of my test worlds. Usually, I test the converter by viewing the result in [GLC Player,](https://sourceforge.net/projects/glc-player/) and it always renders them right side up. For example, here is the 1942 cabinet in its default orientation.

![1942](https://user-images.githubusercontent.com/12615403/212780437-6c5b9b98-a0ee-4231-8bfe-addb6b812a8a.jpg)

**Comment by ghost** [comment] 2023-01-17 01:23
It's not a problem, I just rotate it.

But if you're curious, install Blender (blender.org) and import wavefront (obj) to see it.
I don't understand why glc player is viewing it in another way then blender/godot because it's the same obj file.

Do you have an idea how this is possible?

**Comment by tomysshadow** [comment] 2023-01-17 02:15
According to [Blender's documentation:](https://docs.blender.org/manual/en/2.80/addons/io_scene_obj.html)

> Since many applications use a different axis for ‘Up’, these are axis conversion for these settings, Forward and Up axes – By mapping these to different axes you can convert rotations between applications default up and forward axes.
> 
> Blender uses Y Forward, Z Up (since the front view looks along the +Y direction). For example, it’s common for applications to use Y as the up axis, in that case -Z Forward, Y Up is needed.

In other words, the Wavefront OBJ format has no method of specifying which axis is up, so it comes down to convention. In the Blender Import dialog, ensure that under Transform, Up is set to Z-Up in order to get the correct behaviour. This preset will also remain saved for future imports.

**Comment by ghost** [comment] 2023-01-17 04:22
Thanks! This works. But how did you save the preset? When I restart Blender it's gone :(

**Comment by tomysshadow** [comment] 2023-01-17 06:39
Hit the + next to Operator Presets and give the preset a name, then hit OK.
Now it will be saved as a preset.

**Comment by ghost** [comment] 2023-01-18 22:38
I still don't understand why there needs to be a Up axis.
If I look in the OBJ, I see each vertex is there with X,Y and Z value. 
So if you draw those in any program, shouldn't be the result the same?
Or are different program using different axis for Up so also the other axis are different? 
Why don't they use the same axis?

**Comment by tomysshadow** [comment] 2023-01-18 23:27
The X, Y and Z values are not touched by Shockwave 3D World Converter. They are straight copy pasted from the original world, not rotated or modified in any way. The issue is that 3D modeling tools have historically disagreed on which axis is up.

https://www.reddit.com/r/gamedev/comments/b6ujvb/y_axis_up_or_z_axis_up/?utm_source=share&utm_medium=android_app&utm_name=androidcss&utm_term=1&utm_content=share_button

As this doc called [Which way is up?](https://castle-engine.io/manual_up.php)  explains:

> There are two common conventions for the "up" vector:
> 
> Most 3D modeling software, like Blender, prefers the "up" vector to be +Z.
> 
> This is natural if you think about a level map spread on the XY plane. The Z coordinate is representing the height above the ground.
> 
> glTF, X3D, default OpenGL camera, and various game engines (Castle Game Engine, Unity3d, Unreal Engine) by default prefer the "up" vector to be +Y.
> 
> This makes sense if you think about the screen as being the XY plane. Then if you look straight (in the right-hand coordinate system, as used by X3D, OpenGL and Castle Game Engine) you look in the -Z direction.
> 
> One argument in favor of this convention is that the default camera makes sense for both 2D and 3D games. For 2D games, X goes to the right, Y goes up, and Z doesn't matter (or is used to position layers relative to each other). For 3D games, again X goes to the right, again Y goes up, and Z represents the depth. When your game character jumps, the Y coordinate increases — whether it's a 2D or 3D game.
> 
> As you can imagine, other conventions are possible, as you can pick any 3D vector as "up", and pick anything orthogonal to it as "direction".

Some 3D model formats work around this by standardizing or explicitly specifying the up axis. For example, Collada DAE has an <up_axis> tag which allows tools to specify which way is up, so it can be automatically detected when importing. Wavefront OBJ however has no such benefit, so 3D modeling tools are left to guess which convention is being used. The coordinates are the same, the difference is which axis is up vs. into the screen.

This explains why GLC Player shows the model upright: it assumes Z-Up. Blender is assuming when you import the model that it is Y-Up and is "helpfully" rotating it to Z-Up for you. You don't want this, so you need to explicitly specify that it is already Z-Up.

**Comment by tomysshadow** [comment] 2023-01-22 01:51
Closing this because the converter is working correctly and directly copying the coordinates of the original world. The axis needs to be set correctly on import.

**Closed as completed by tomysshadow** 2023-01-22 01:51 UTC
