### ISSUE TITLE
big W3D model: missing textures

### ISSUE THREAD

**Issue by ghost** [tomysshadow/Shockwave-3D-World-Converter#6] opened 2023-01-16 19:12 UTC
Hi

I'm now trying big W3D models and it seems textures are missing.

https://www.mameworld.info/3darcade/arcades/arcades.htm

Try spaceport.

It should look like this:

![afbeelding](https://user-images.githubusercontent.com/122493908/212750238-1027817d-97f2-4f7d-8077-6ad5a2768891.png)

After converting to OBJ and MTL, some textures are not present and after loading into Godot engine, I see this:

- red cross is missing
- you see inside the building more things are missing (same texture as outside)
- not sure if the lamps are textures
- (the cabinets inside the building are not belonging to this model)

![afbeelding](https://user-images.githubusercontent.com/122493908/212750841-29fed37b-d436-45e9-bfd2-ebe844d87e83.png)

**Comment by tomysshadow** [comment] 2023-01-16 23:28
Hi again. I imported spaceworld.W3D into Director, to see how it renders out this world, and it looks almost identical to your second screenshot.

![Spaceport](https://user-images.githubusercontent.com/12615403/212779581-ead25223-1cd6-44f9-ba47-42c8668a04d2.jpg)

This is a screenshot of how the world looks in Shockwave 3D itself, so I know it is not a conversion issue. It's likely the case that the application that loads this world applies the remaining textures via a Lingo script at runtime.

If you can open the Message Window during playback, you can export the world with the textures applied at runtime by using the `savew3d` handler (in Shockwave 11+ only.)

**Comment by ghost** [comment] 2023-01-17 01:18
Is it adobe director 11.5 like you said or which version you have?
I found it on archive.org and going to install it.

Can you look inside the zip file please? I found there more W3D models! I think those werd put together to make it look like screenshot 1.

**Comment by tomysshadow** [comment] 2023-01-17 01:20
I did see the other worlds but I assumed you wanted to convert the main one
(which converts correctly.)

Yes, for this project I'm using 11.5 (patched to the latest version,
11.5.9.)

**Comment by ghost** [comment] 2023-01-17 01:24
So Lingo can 'glue' together different models at runtime?
And this is how the final result was made you think?

**Comment by tomysshadow** [comment] 2023-01-17 01:34
Indeed. Shockwave 3D is very flexible, it's possible to combine worlds,
modify shaders, textures, cameras, lighting, level of detail, and all kinds
of tiny details at runtime. Some Director based videogames don't even use
world files, instead starting with a blank world and using scripts to
generate the meshes to save on filesize. For example, the game Laffy Taffy
3D Pyramid generates a 3D maze from a list of points in space.

**Comment by ghost** [comment] 2023-01-17 01:42
This is also off-topic but I don't know where to ask.
Do you have a tool or a way to get the Lingo scripts from a director application or anything else that could be inside?
I try to find out how 3D arcade was made, see

https://www.mameworld.info/3darcade

Click on 'frontend' and download it

**Comment by tomysshadow** [comment] 2023-01-17 02:07
Typically, you would need the source code (DIR type file) to open in Director. The final result is compiled so the script text is made empty when publishing, and Director will not typically let you open a protected movie (DXR or DCR type files.) I do have a [Movie Restorer Xtra](https://github.com/tomysshadow/Movie-Restorer-Xtra/releases) which allows Director to open protected movies, although the script text will still be empty. You would also need to export the Movies from the Projector (EXE type file,) which can be accomplished with Valentin's Unpack utility: https://valentin.dasdeck.com/lingo/unpack/

It's not advisable to re-publish a Shockwave Movie that has been opened this way. Shockwave Movies are a lossy format, so re-publishing them will cause all media to be recompressed and lose quality.

**Comment by tomysshadow** [comment] 2023-01-22 01:50
Closing this because the converter is working as intended.

**Closed as completed by tomysshadow** 2023-01-22 01:50 UTC
